version: '3'

services:

  db:
    image: postgres
    restart: always
    environment:
      - POSTGRES_DB=road_analytics
      - POSTGRES_USER=road_analytics_admin
      - POSTGRES_PASSWORD=root
    ports:
      - '5432:5432'
    volumes:
      - ./init/postgres:/docker-entrypoint-initdb.d:ro
      - ./storage/postgres:/var/lib/postgresql/data:rw


